import React from 'react';
import { 
  BookOpen, 
  Download, 
  FileText, 
  Sparkles,
  ChevronRight
} from 'lucide-react';
import confetti from 'canvas-confetti';

export default function JournalCard({ onOpenJournal }) {
  const handleExportGPX = (e) => {
    e.stopPropagation();
    confetti({ particleCount: 35, spread: 50, origin: { y: 0.8 } });
    const gpx = `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="Touch Grass AI">
  <trk><name>Bear Mountain Hawk Ridge Trail</name><trkseg><trkpt lat="41.3129" lon="-73.9882"><ele>180</ele></trkpt></trkseg></trk>
</gpx>`;
    const blob = new Blob([gpx], { type: 'application/gpx+xml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `bear-mountain-trail.gpx`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleExportMarkdown = (e) => {
    e.stopPropagation();
    confetti({ particleCount: 45, spread: 60, origin: { y: 0.8 } });
    const md = `# Touch Grass Field Report
**Date:** Oct 12, 2026
**Trail:** Kedarkantha Summit Ridge (12.5 mi, 3,810 m)
**Species Identified:**
- Himalayan Monal (Lophophorus impejanus) at 07:15 AM (3,850 Hz)
- Koklass Pheasant (Pucrasia macrolopha) at 08:45 AM (2,400 Hz)
**Microclimate (TabPFN):** 94% frost danger window, 92% golden birch saturation
*Generated by Touch Grass AI — Screen-On Time: 42s*`;
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `kedarkantha-field-report.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div 
      onClick={onOpenJournal}
      className="outdoor-card p-4 bg-[#F2F8F4]/95 border-[#C8DEC8] cursor-pointer outdoor-card-interactive flex flex-col justify-between"
    >
      {/* Header */}
      <div className="flex items-center justify-between mb-2.5">
        <div className="flex items-center gap-2">
          <div className="w-6 h-6 rounded-lg bg-[#E7A94B]/20 flex items-center justify-center text-[#E7A94B]">
            <BookOpen className="w-3.5 h-3.5" />
          </div>
          <h3 className="text-xs font-bold text-[#20332A] truncate">
            Field Journal & Bio-Vault
          </h3>
        </div>

        <span className="text-[10px] text-[#3F7D5A] font-bold hover:underline flex items-center">
          View All <ChevronRight className="w-3 h-3" />
        </span>
      </div>

      <div className="flex items-center justify-between gap-3">
        {/* 3 Observation Mini Cards */}
        <div className="flex items-center gap-2 overflow-x-auto py-0.5">
          {/* Himalayan Monal */}
          <div className="flex items-center gap-1.5 p-1 pr-2 rounded-xl bg-[#EBF5EE] border border-[#C8DEC8] shrink-0">
            <img 
              src="/assets/journal_bird.jpg" 
              alt="Himalayan Monal"
              className="w-7 h-7 rounded-lg object-cover" 
            />
            <div className="text-[9px] leading-tight">
              <span className="font-bold text-[#20332A] block">Himalayan Monal</span>
              <span className="text-[#6F7B72]">07:15 AM</span>
            </div>
          </div>

          {/* Koklass Pheasant */}
          <div className="flex items-center gap-1.5 p-1 pr-2 rounded-xl bg-[#EBF5EE] border border-[#C8DEC8] shrink-0">
            <img 
              src="/assets/journal_hawk.jpg" 
              alt="Koklass Pheasant"
              className="w-7 h-7 rounded-lg object-cover" 
            />
            <div className="text-[9px] leading-tight">
              <span className="font-bold text-[#20332A] block">Koklass Pheasant</span>
              <span className="text-[#6F7B72]">08:45 AM</span>
            </div>
          </div>

          {/* Kedarkantha Summit */}
          <div className="flex items-center gap-1.5 p-1 pr-2 rounded-xl bg-[#EBF5EE] border border-[#C8DEC8] shrink-0">
            <img 
              src="/assets/journal_viewpoint.jpg" 
              alt="Kedarkantha Summit"
              className="w-7 h-7 rounded-lg object-cover" 
            />
            <div className="text-[9px] leading-tight">
              <span className="font-bold text-[#20332A] block">Kedarkantha Summit</span>
              <span className="text-[#6F7B72]">11:30 AM</span>
            </div>
          </div>
        </div>

        {/* Export Buttons */}
        <div className="flex flex-col gap-1 shrink-0">
          <button
            onClick={handleExportGPX}
            className="px-2.5 py-1 rounded-lg border border-[#C8DEC8] hover:border-[#3F7D5A] bg-[#F2F8F4] hover:bg-[#EBF5EE] text-[10px] font-bold text-[#20332A] flex items-center gap-1 transition shadow-sm"
          >
            <Download className="w-3 h-3 text-[#3F7D5A]" />
            <span>Export GPX</span>
          </button>

          <button
            onClick={handleExportMarkdown}
            className="px-2.5 py-1 rounded-lg border border-[#C8DEC8] hover:border-[#3F7D5A] bg-[#F2F8F4] hover:bg-[#EBF5EE] text-[10px] font-bold text-[#20332A] flex items-center gap-1 transition shadow-sm"
          >
            <FileText className="w-3 h-3 text-[#285943]" />
            <span>Export Markdown</span>
          </button>
        </div>
      </div>
    </div>
  );
}
